version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://dataclean_user:dataclean_pass@db:5432/dataclean_db
      - CLOUD_STORAGE_ENABLED=false
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8507:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=dataclean_db
      - POSTGRES_USER=dataclean_user
      - POSTGRES_PASSWORD=dataclean_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_backup:/backup
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataclean_user -d dataclean_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  postgres_data:
  # redis_data:
